services:
  - type: web
    name: welllab-telegram-bot
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HOTLINE_TUYEN_TREN
        sync: false
      - key: LINK_KENH_TELEGRAM
        sync: false
      - key: LINK_FANPAGE
        sync: false
      - key: LINK_WEBSITE
        sync: false
      - key: UPLINE_CHAT_ID
        sync: false
      - key: LOG_SHEET_WEBHOOK_URL
        sync: false
